FROM --platform=linux/amd64 latex-alpine-base:latest-amd64

#USER 0
#COPY ./post_livetex_install.sh /tmp/post_livetex_install.sh
#RUN /tmp/post_livetex_install.sh
#
#USER latex
#COPY ./initialize_fonts.sh /tmp/initialize_fonts.sh
#RUN /tmp/initialize_fonts.sh